# Generated by Django 3.2.8 on 2021-11-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_auto_20211028_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userdisplay',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
